const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<title>PSX Mobile Intelligence</title><style>
:root{color-scheme:dark;--bg:#071019;--panel:#101d29;--line:#263746;--text:#eef6ff;--muted:#91a4b5;--green:#36d399;--amber:#fbbf24;--red:#fb7185;--blue:#60a5fa}*{box-sizing:border-box}body{margin:0;background:linear-gradient(160deg,#071019,#0b1723);color:var(--text);font-family:Inter,system-ui,sans-serif}.wrap{max-width:900px;margin:auto;padding:18px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center}.brand{font-size:20px;font-weight:800}.sub,.muted{color:var(--muted);font-size:13px}.panel,.card{background:rgba(16,29,41,.96);border:1px solid var(--line);border-radius:16px;padding:16px;margin-top:14px;box-shadow:0 10px 30px #0004}.hidden{display:none!important}input,button{width:100%;padding:13px;border-radius:10px;border:1px solid var(--line);background:#09131d;color:var(--text);margin-top:10px}button{background:#1263b7;font-weight:750;cursor:pointer}.smallbtn{width:auto;padding:9px 13px;margin:0}.danger{background:#7f1d1d}.banner{border-radius:12px;padding:12px;margin-top:14px;font-weight:750}.fresh{background:#063b2c;color:#a7f3d0}.stale{background:#551b26;color:#fecdd3}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.card{margin-top:0}.row{display:flex;justify-content:space-between;gap:12px;margin:7px 0}.symbol{font-size:22px;font-weight:850}.pill{display:inline-block;border-radius:999px;padding:4px 9px;font-size:11px;font-weight:800;background:#24384a}.buy{color:var(--green)}.watch{color:var(--amber)}.reject{color:var(--red)}.metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.metric{background:#09131d;padding:10px;border-radius:10px;text-align:center}.metric b{display:block;font-size:18px}.reason{font-size:12px;line-height:1.45;color:#c8d4df}.section{margin:22px 0 10px}.section h2{font-size:17px;margin:0}.empty{padding:18px;color:var(--muted);border:1px dashed var(--line);border-radius:12px}.critical{color:var(--red);font-weight:800}@media(max-width:520px){.wrap{padding:12px}.metrics{grid-template-columns:1fr 1fr}.top{align-items:flex-start}}
</style></head><body><main class="wrap">
<div class="top"><div><div class="brand">PSX Intelligence</div><div class="sub">Authenticated mobile read-only dashboard</div></div><button id="logout" class="smallbtn danger hidden">Logout</button></div>
<section id="login" class="panel"><h2>Secure Login</h2><div class="muted">Supabase account email aur password use karein.</div><input id="email" type="email" autocomplete="username" placeholder="Email"><input id="password" type="password" autocomplete="current-password" placeholder="Password"><button id="loginButton">Login</button><p id="loginError" class="critical"></p></section>
<section id="app" class="hidden"><div id="freshness" class="banner stale">Snapshot verify ho raha hai…</div><div class="panel"><div class="top"><div><b id="marketDate">—</b><div id="generated" class="muted">—</div></div><button id="refresh" class="smallbtn">Refresh</button></div><div class="metrics"><div class="metric"><b id="readyCount">0</b>Entry Ready</div><div class="metric"><b id="watchCount">0</b>Priority Watch</div><div class="metric"><b id="rejectCount">0</b>Rejected</div></div></div>
<section class="section"><h2 class="buy">Entry Ready</h2></section><div id="ready" class="grid"></div>
<section class="section"><h2 class="watch">Priority Watch — BUY Permission Nahi</h2></section><div id="watch" class="grid"></div>
<section class="section"><h2>Ranked Market View</h2></section><div id="ranked" class="grid"></div></section>
</main><script>
const SUPABASE_URL=__SUPABASE_URL__;const ANON_KEY=__ANON_KEY__;const STALE_SECONDS=1800;let session=JSON.parse(localStorage.getItem('psx_cloud_session')||'null');
const $=id=>document.getElementById(id);const esc=v=>String(v??'—').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function setMode(logged){$('login').classList.toggle('hidden',logged);$('app').classList.toggle('hidden',!logged);$('logout').classList.toggle('hidden',!logged)}
async function api(path,options={}){const headers={apikey:ANON_KEY,'content-type':'application/json',...(options.headers||{})};if(session?.access_token)headers.authorization='Bearer '+session.access_token;const r=await fetch(SUPABASE_URL+path,{...options,headers});if(r.status===401){session=null;localStorage.removeItem('psx_cloud_session');setMode(false);throw new Error('Session expired. Dobara login karein.')}const t=await r.text();if(!r.ok)throw new Error(t||('HTTP '+r.status));return t?JSON.parse(t):null}
async function login(){try{$('loginError').textContent='';const data=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});session=data;localStorage.setItem('psx_cloud_session',JSON.stringify(data));setMode(true);await load()}catch(e){$('loginError').textContent='Login failed: '+e.message}}
function n(v,d=2){const x=Number(v);return Number.isFinite(x)?x.toFixed(d):'—'}
function card(r,type){const cls=type==='ready'?'buy':type==='watch'?'watch':'';return '<article class="card"><div class="row"><span class="symbol '+cls+'">'+esc(r.symbol)+'</span><span class="pill">'+esc(r.decision||r.status)+'</span></div><div class="row"><span>Price</span><b>Rs '+n(r.price??r.close)+'</b></div><div class="row"><span>Day</span><b class="'+(Number(r.dayChangePercent)<0?'reject':'buy')+'">'+n(r.dayChangePercent)+'%</b></div><div class="row"><span>Score</span><b>'+n(r.scannerScore,0)+'</b></div><div class="row"><span>Stop / T1</span><b>'+n(r.stopLoss)+' / '+n(r.target1)+'</b></div><div class="row"><span>Volume Ratio</span><b>'+n(r.volumeRatio)+'</b></div><p class="reason">'+esc(r.reason||r.intradayQualityReason||'Evidence available in full snapshot.')+'</p></article>'}
function renderRows(id,rows,type,limit){const list=Array.isArray(rows)?rows.slice(0,limit):[];$(id).innerHTML=list.length?list.map(r=>card(r,type)).join(''):'<div class="empty">Is category mein abhi koi candidate nahi.</div>'}
async function load(){try{const rows=await api('/rest/v1/cloud_scanner_latest?select=revision,generated_at,published_at,payload&singleton_id=eq.1&limit=1');if(!rows?.length)throw new Error('Abhi cloud snapshot publish nahi hua.');const s=rows[0].payload;const age=Math.max(0,(Date.now()-Date.parse(s.generatedAt||rows[0].generated_at))/1000);const stale=age>STALE_SECONDS;$('freshness').className='banner '+(stale?'stale':'fresh');$('freshness').textContent=stale?'STALE SNAPSHOT — BUY PERMISSION BLOCKED. Fresh scan ka intezar karein.':'FRESH SNAPSHOT — phir bhi sirf Entry Ready ko execution candidate samjhein.';$('marketDate').textContent='Market: '+(s.marketDate||'—')+' | '+(s.marketState?.readiness||'UNKNOWN');$('generated').textContent='Generated: '+new Date(s.generatedAt).toLocaleString()+' | Cloud revision '+rows[0].revision;$('readyCount').textContent=s.marketState?.executableBuyCount??0;$('watchCount').textContent=s.marketState?.priorityWatchCount??0;$('rejectCount').textContent=s.marketState?.rejectedCount??0;renderRows('ready',stale?[]:s.entryReady,'ready',20);renderRows('watch',s.priorityWatch,'watch',20);renderRows('ranked',s.ranked,'ranked',20)}catch(e){$('freshness').className='banner stale';$('freshness').textContent='Cloud data unavailable — BUY PERMISSION BLOCKED: '+e.message}}
$('loginButton').onclick=login;$('refresh').onclick=load;$('logout').onclick=async()=>{try{await api('/auth/v1/logout',{method:'POST'})}catch{}session=null;localStorage.removeItem('psx_cloud_session');setMode(false)};setMode(Boolean(session?.access_token));if(session?.access_token)load();
</script></body></html>`;

Deno.serve(() => {
  const url = Deno.env.get("SUPABASE_URL") || "";
  const anon = Deno.env.get("SUPABASE_ANON_KEY") || "";
  const body = html
    .replace("__SUPABASE_URL__", JSON.stringify(url))
    .replace("__ANON_KEY__", JSON.stringify(anon));
  return new Response(body, {
    headers: {
      "content-type": "text/html; charset=utf-8",
      "cache-control": "no-store",
      "content-security-policy": "default-src 'none'; connect-src " + url + "; style-src 'unsafe-inline'; script-src 'unsafe-inline'; img-src 'self' data:; base-uri 'none'; frame-ancestors 'none'; form-action 'none'",
      "referrer-policy": "no-referrer",
      "x-content-type-options": "nosniff"
    }
  });
});
